RM.MVCWebUI/Areas/FilterAdmin/Controllers/CarTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RM.BL.Car;
using RM.Core.Car;
using RM.DAL.Car;

namespace RM.MVCWebUI.Areas.FilterAdmin.Controllers
{
    public class CarTypeController : Controller
    {
        private readonly FilterCarType _carType;

        public CarTypeController(FilterCarType carType)
        {
            _carType = carType;
        }
        // GET: FilterAdmin/CarType
        public ActionResult Index()
        {
            var result = _carType.GetAllCarTypes();
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CarType carType)
        {
            if (ModelState.IsValid)
            {
                _carType.AddCarType(carType);
                return RedirectToAction("Index");
            }

            return View(carType);
        }

        public ActionResult Delete(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var result = _carType.GetCarType(id.Value);

            if (result==null)
            {
                return HttpNotFound();
            }

            return View(result);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _carType.DeleteCarType(id);
            return RedirectToAction("Index");
        }
    }
}

RM.MVCWebUI/Areas/FilterAdmin/Views/CarType/Create.cshtml
@model RM.Core.Car.ICarType

@{
    ViewBag.Title = "ایجاد";
    Html.EnableClientValidation(true);
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">نوع خودرو</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item">
                        خودرو
                    </li>
                    <li class="breadcrumb-item">
                        نوع خودرو
                    </li>
                    <li class="breadcrumb-item active">ایجاد</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-1">

                <!-- Horizontal Form -->
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">ایجاد نوع جدید</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <div class="card-body">
                                @Html.ValidationSummary(true, "", new {@class = "text-danger"})

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Type, htmlAttributes: new {@class = "control-label col-md-2"})
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Type, new {htmlAttributes = new {@class = "form-control"}})
                                        @Html.ValidationMessageFor(model => model.Type, "", new {@class = "text-danger"})
                                    </div>
                                </div>
                            </div>

                            <!-- /.card-body -->
                            <div class="card-footer">
                                <input type="submit" value="ایجاد" class="btn btn-info"/>
                                <a class="btn btn-default float-left" href="@Url.Action("Index")">لغو</a>
                            </div>
                            <!-- /.card-footer -->

                        </div>
                    }

                </div>
                <!-- /.card -->

            </div>

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->

RM.MVCWebUI/Areas/FilterAdmin/Views/CarType/Delete.cshtml
@model RM.Core.Car.ICarType

@{
    ViewBag.Title = "Delete";
}


<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">نوع خودرو</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item">
                        خودرو
                    </li>
                    <li class="breadcrumb-item">
                        نوع خودرو
                    </li>
                    <li class="breadcrumb-item active">حذف</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-1">

                <!-- Horizontal Form -->
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">حذف</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="form-horizontal">
                        <div class="card-body">

                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Type)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Type)
                                </dd>

                            </dl>

                        </div>

                        <!-- /.card-body -->
                        <div class="card-footer">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <input type="submit" value="حذف" class="btn btn-danger"/>
                                <a class="btn btn-default float-left" href="@Url.Action("Index")">لغو</a>
                            }

                        </div>
                        <!-- /.card-footer -->

                    </div>

                </div>
                <!-- /.card -->

            </div>

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->

RM.MVCWebUI/Areas/FilterAdmin/Views/CarType/Index.cshtml
@model IEnumerable<RM.Core.Car.ICarType>
@{
    ViewBag.Title = "Index";
}

@section PageScript
{
    <!-- Slimscroll -->
    <script src="~/Scripts/Admin/jquery.slimscroll.min.js"></script>
    <!-- FastClick -->
    <script src="~/Scripts/Admin/fastclick.min.js"></script>
}

@{
    ViewBag.Title = "Index";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">نوع خودرو</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item">
                       خودرو
                    </li>
                    <li class="breadcrumb-item active">نوع خودرو</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->

<div class="content">
    <div class="container-fluid">
        <div class="row">
          
            <div class="col-12">
                <p>
                    <a class="btn btn-success" id="btnNewGroup" href="@Url.Action("Create")"><i class="fas fa-plus"></i> افزودن نوع جدید </a>
                </p>
                <div class="card">

                    <div class="card-body p-0">

                        <table class="table">
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>نوع خودرو</th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Type</td>
                                    <td>
                                        <a class="btn btn-warning" href="#"><i class="fas fa-edit"></i></a> |
                                        <a class="btn btn-danger" href="@Url.Action("Delete","CarType",new {id=@item.Id})"><i class="fas fa-trash-alt"></i></a>
                                    </td>
                                </tr>

                            }
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->